name: SetOnHead
version: '1.4'
main: com.ashkiano.setonhead.SetOnHead
api-version: '1.16'
author: AshKiano
commands:
  setonhead:
    description: Sets the item in your hand on your head.
    usage: /<command>